### ISSUE TITLE
Library breaks the build on XCode 16.3

### ISSUE THREAD

**Issue by edgar-zigis** [hmlongco/Factory#309]
Hello,

after updating the XCode to the recent version of 16.3, the build starts emitting compilation errors:
```
Undefined symbol: associated type descriptor for Testing.Trait.TestScopeProvider
Undefined symbol: protocol descriptor for Testing.SuiteTrait
Undefined symbol: method descriptor for Testing.SuiteTrait.isRecursive.getter : Swift.Bool
Undefined symbol: (extension in Testing):Testing.SuiteTrait< where A: Testing.TestScoping>.scopeProvider(for: Testing.Test, testCase: Testing.Test.Case?) -> A?
```
this is due to the fact that your package utilizes new Apple `Testing.framework` and it requires the app integrating your package also to include that framework in the build dependencies. After including the framework to the target, the application is successfully building only on the physical devices as by default it does not include pre-built frameworks for iOS simulators, therefore your package makes simulator builds impossible. 

Unfortunately it forces us to rollback from the Factory back to Resolver for now. Everything was working fine in the previous XCode versions.

**Comment by hmlongco** [comment]
Going to need more information on project setup, etc.. The FactoryDemo project imports FactoryKit and builds and runs on the simulator under 16.3 so it's not strictly a Xcode issue. 

The unit tests for demo also appear to run just fine.

Anyone else seeing issues?

**Comment by hmlongco** [comment]
You could also just roll Factory back to 2.4.5 or so.

**Comment by edgar-zigis** [comment]
For now I have removed FactoryTesting from the included dependencies and it works.
Project configuration is simple as I have started it quite recently. Not modularized, no custom build settings (except added linker flag of -ObjC) or build phases (except Crashlytics configuration). Project was created for SwiftUI with tests enabled by default, however no test targets are added yet. Base architecture arm64, base SDK iOS (minimum version 16.6), no support for multiplatform.

**Comment by hmlongco** [comment]
@edgar-zigis "however no test targets are added yet"

Bingo. FactoryTesting is a Swift Testing trait, and as such that library should be added to the **test target**, and NOT to the main app or other targets.
